language: objective-c
xcode_project: adium-mattermost.xcodeproj
xcode_scheme: adium-mattermost
before_install:
  - brew install openssl
  - cd adium; make | tail -n 40; cd ..
  - cd discount; ./configure.sh; make; cd ..
  - git apply --whitespace=nowarn patch.diff